### ISSUE TITLE
ghc-mod crashed on command info src/Logger.hs MaybeT

### ISSUE THREAD

**Issue by shouya** [hoovercj/vscode-ghc-mod#39]
When I hover on any word in the editor, this error notification shows and no tooltip is shown.

So I'm having the latest version of vscode (1.7.2) and ghc-mod extension (1.0.1), with ghc-mod version 5.6.0.0 compiled by GHC 8.0.1.

Here's the output from the ghc-mod-server:

```
TypeError: Cannot read property 'apply' of null
    at CallbackList.invoke (/Users/shou/.vscode/extensions/hoovercj.vscode-ghc-mod-1.0.1/server/node_modules/vscode-languageserver/node_modules/vscode-jsonrpc/lib/events.js:103:38)
    at Emitter.fire (/Users/shou/.vscode/extensions/hoovercj.vscode-ghc-mod-1.0.1/server/node_modules/vscode-languageserver/node_modules/vscode-jsonrpc/lib/events.js:167:36)
    at /Users/shou/.vscode/extensions/hoovercj.vscode-ghc-mod-1.0.1/server/node_modules/vscode-languageserver/lib/main.js:287:39
    at handleNotification (/Users/shou/.vscode/extensions/hoovercj.vscode-ghc-mod-1.0.1/server/node_modules/vscode-languageserver/node_modules/vscode-jsonrpc/lib/main.js:267:17)
    at process.callback (/Users/shou/.vscode/extensions/hoovercj.vscode-ghc-mod-1.0.1/server/node_modules/vscode-languageserver/node_modules/vscode-jsonrpc/lib/main.js:363:13)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Any hints on what's going on? What can I do to fix it?

**Comment by shouya** [comment]
I don't have anything about ghc-mod written in my configuration yet, so all is on its default.

**Comment by hoovercj** [comment]
Hi @shouya, unfortunately the stack trace you found is entirely in vscode internals so I can't get much information from it.

Can you try adding this setting (workspace or user): `"haskell.ghcMod.logLevel": "log"`

**Comment by shouya** [comment]
I have set the new log level and restarted VSCode, but the issue persist and the output is still the same.

Is there another place other than the output pane (⇧⌘U) where I can see more logs?

**Comment by hoovercj** [comment]
You can open the developer tools (in the command palette" "toggle developer tools") and see the logs there. This was written before I knew about output channels (or maybe they didn't exist yet). Maybe I should change that :-)

**Comment by shouya** [comment]
The issue is now fixed. Thank you for the suggesting.

I figured out in the developer console that it was because I have a missing dependency so ghc-mod cannot process my file. After executing `cabal install`, the problem is gone.

IMHO, if it can output something more friendly instead of crashing alone, then that would be great. Thanks again!

**Comment by hoovercj** [comment]
I'm glad you've sorted it out. I opened an issue about making the logging more accessible.

Please open a new issue if you have now problems in the future and I hope you enjoy the extension!
