### ISSUE TITLE
When open a folder ghc-mod crashes

### ISSUE THREAD

**Issue by OnurGumus** [hoovercj/vscode-ghc-mod#44]
For individual files this extension works fine. But when I open a folder I am getting below error:
```
TypeError: Cannot read property 'apply' of null
    at CallbackList.invoke (C:\Users\onur.gumus\.vscode\extensions\hoovercj.vscode-ghc-mod-1.0.1\server\node_modules\vscode-languageserver\node_modules\vscode-jsonrpc\lib\events.js:103:38)
    at Emitter.fire (C:\Users\onur.gumus\.vscode\extensions\hoovercj.vscode-ghc-mod-1.0.1\server\node_modules\vscode-languageserver\node_modules\vscode-jsonrpc\lib\events.js:167:36)
    at C:\Users\onur.gumus\.vscode\extensions\hoovercj.vscode-ghc-mod-1.0.1\server\node_modules\vscode-languageserver\lib\main.js:287:39
    at handleNotification (C:\Users\onur.gumus\.vscode\extensions\hoovercj.vscode-ghc-mod-1.0.1\server\node_modules\vscode-languageserver\node_modules\vscode-jsonrpc\lib\main.js:267:17)
    at process.callback (C:\Users\onur.gumus\.vscode\extensions\hoovercj.vscode-ghc-mod-1.0.1\server\node_modules\vscode-languageserver\node_modules\vscode-jsonrpc\lib\main.js:363:13)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by OnurGumus** [comment]
Also this started to happen after upgrading to platform to Haskell 8.01 with ghc-mod 5.7
This is on Windows btw.

**Comment by OnurGumus** [comment]
I think this is an environment issue.
